# action.yml
name: 'trigger-deploy-action'
description: 'Trigger a deployment of the jaws2 framework'
inputs:
  repo_name:
    description: The name of the repo to execute in the format org/repo_name
    required: True
  github_token:
    description: 'The github PAT token for the remote repository'
    required: True
  git_ref:
    description: 'The git reference to trigger a deployment for'
    required: True
  environment: 
    description: 'The environment to run against'
    required: True
  testrail_run_id:
    description: 'The testrail run id'
    required: False
outputs:
   status:
    description: "The Success/Failure of the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
